### ISSUE TITLE
Warning: Illegal string offset 'colspan' in simplified_menu_admin_preprocess_table() (line 59 of simplified_menu_admin.module)

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/simplified_menu_admin#1]
Downloaded and enabled latest master. Tried going to a random menu edit page (`/admin/structure/menu/manage/main-menu/edit` for example) and got a WSOD. Navigated to `/admin/structure/` and got this:

```
Warning: Illegal string offset 'colspan' in simplified_menu_admin_preprocess_table() (line 59 of .../modules/simplified_menu_admin/simplified_menu_admin.module).
```

Could be something or could be nothing because after that and a single page refresh all worked fine (perhaps needed cache clear before initial use). Searched the original module queue in d.org for a respective issue, but there was none.

**Comment by biolithic** [comment]
Thanks for checking.  I have multiple modules with porting issues to fix
up, will get to it.

**Comment by klonos** [comment]
No worries. Thanx for porting this. It helps get closer into D8 feature parity.

**Comment by laryn** [comment]
This should be fixed in the latest dev.
