### ISSUE TITLE
Delete button missing from the menu edit page.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/simplified_menu_admin#2]
This is basically the same as https://www.drupal.org/node/2287219

The delete button is missing from the built-in menus that come with core out of the box, ...and the "Delete menu" menu item from the Admin bar (`/admin/structure/menu/manage/management/delete`) leads to a 403 "Access denied" error page.

For custom menus created by the user, the button is there but deleting the menu causes #1

Now, `/admin/structure/menu` gives a WSOD.

**Comment by klonos** [comment]
...disabling the module, then uninstalling it and finally a cache clear restored the `/admin/structure/menu` with no WSOD any more.

**Comment by klonos** [comment]
...now I'm stuck to a WSOD in the Menus admin page every time I enable this module. I'm afraid I won't be able to test anymore until this issue is solved.

**Comment by laryn** [comment]
@klonos I think this is by design since those menus are owned by the core menu module -- you can't delete them even if this module is not enabled.
